spring:
  datasource:
    url: jdbc:mysql://localhost:4444/tpfoyerarctic?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Use MySQL 8 dialect

server:
  port: 8080
  servlet:
    context-path: /tpfoyer  # All endpoints will be prefixed with /tpfoyer

# Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs  # Endpoint for OpenAPI documentation
  swagger-ui:
    path: /swagger-ui.html  # Correct path for Swagger UI